version: '3.9'
services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: gridmap
      POSTGRES_USER: gridmap
      POSTGRES_PASSWORD: gridmappass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://gridmap:gridmappass@db/gridmap
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3  
  celery_worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    restart: unless-stopped
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://gridmap:gridmappass@db/gridmap
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started

  celery_beat:
    build: .
    command: celery -A app.tasks beat --loglevel=info
    restart: unless-stopped
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://gridmap:gridmappass@db/gridmap
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
volumes:
  pgdata:
